---
theme: hugo-journal
title: "CodeVerse"
baseurl: "http://mpas.github.io/"
paginate: 10

params:
    # blog information
    author: "Marco Pas"

    # social links
    twitter: "marcopas"
    github: "mpas"
    facebook: "marco.pasopas"
    delicious: "marcopas"

taxonomies:
    tag: "tags"
    category: "categories"

...