baseurl     = "http://mpas.github.io/"  # the baseurl for your website
title       = "CodeVerse"               # blog title
paginate    = 10                        # the number of posts on a page

[permalinks]
    post = "/blog/:year/:month/:day/:title/"

[params]
    # name of the site author; used in header meta information
    author = "Marco Pas"

    # social links, used in footer, these must be full URLs.
    twitter = "https://twitter.com/marcopas"
    github = "https://github.com/mpas"
    facebook = "https://www.facebook.com/marco.pasopas"
    delicious = "https://delicious.com/marcopas"

[params.theme]
    inverse = false     # indicating if the theme should use inversed colors
    name = "journal"   # name of the theme to use

    # list of possible theme names that can be used
    # name = "cerulean"
    # name = "cosmo"
    # name = "cyborg"
    # name = "default"
    # name = "flatly"
    # name = "journal"
    # name = "lumen"
    # name = "paper"
    # name = "readable"
    # name = "sandstone"
    # name = "simplex"
    # name = "slate"
    # name = "spacelabs"
    # name = "superhero"
    # name = "united"
    # name = "yeti"
