name = "hugo-journal"
license = "MIT"
licenselink = "http://sm.mit-license.org/"
description = "Hugo theme based on Twitter BootStrap and Journal CSS theme"
tags = ["post", "category"]
categories = ["featured"]
min_version = 0.13

[author]
    name = "Marco Pas"
    email = "marco.pasopas@gmail.com"